// ============================================================
// FSS FORM ANALYTICS — SEED DATA
// Pre-loaded 13 months of realistic mock data (May 2025 – May 2026)
// May 2026 matches the exact figures from the provided PDF return.
// ============================================================

const SEED_SUBMISSIONS = [
  {
    id: 'sub-2025-05',
    month: '2025-05',
    submittedBy: 'FSO Rajesh Kumar',
    submittedAt: '2025-06-02T10:30:00',
    district: 'Chennai',
    designation: 'Food Safety Officer',
    answers: {
      q1:  { text: '389', files: [] },
      q2:  { text: '18', files: [] },
      q3:  { text: '3', files: [] },
      q4:  { text: '3', files: [] },
      q5:  { text: '0', files: [] },
      q6:  { text: '0', files: [] },
      q7:  { text: '1', files: [] },
      q8:  { text: '1', files: [] },
      q9:  { text: '0', files: [] },
      q10: { text: '2', files: [] },
      q11: { text: '1', files: [] },
      q12: { text: '0', files: [] },
      q13: { text: '0', files: [] },
      q14: { text: '0', files: [] },
      q15: { text: '0', files: [] },
      q16: { text: 'Routine inspections completed. 3 samples sent to lab.', files: [] }
    }
  },
  {
    id: 'sub-2025-06',
    month: '2025-06',
    submittedBy: 'FSO Rajesh Kumar',
    submittedAt: '2025-07-03T09:00:00',
    district: 'Chennai',
    designation: 'Food Safety Officer',
    answers: {
      q1:  { text: '390', files: [] },
      q2:  { text: '22', files: [] },
      q3:  { text: '4', files: [] },
      q4:  { text: '4', files: [] },
      q5:  { text: '1', files: [] },
      q6:  { text: '0', files: [] },
      q7:  { text: '0', files: [] },
      q8:  { text: '1', files: [] },
      q9:  { text: '1', files: [] },
      q10: { text: '3', files: [] },
      q11: { text: '1', files: [] },
      q12: { text: '0', files: [] },
      q13: { text: '1', files: [] },
      q14: { text: '0', files: [] },
      q15: { text: '0', files: [] },
      q16: { text: 'One unsafe sample detected (packaged snacks). FBO warned.', files: [] }
    }
  },
  {
    id: 'sub-2025-07',
    month: '2025-07',
    submittedBy: 'FSO Rajesh Kumar',
    submittedAt: '2025-08-04T11:00:00',
    district: 'Chennai',
    designation: 'Food Safety Officer',
    answers: {
      q1:  { text: '390', files: [] },
      q2:  { text: '19', files: [] },
      q3:  { text: '5', files: [] },
      q4:  { text: '4', files: [] },
      q5:  { text: '0', files: [] },
      q6:  { text: '1', files: [] },
      q7:  { text: '1', files: [] },
      q8:  { text: '2', files: [] },
      q9:  { text: '0', files: [] },
      q10: { text: '2', files: [] },
      q11: { text: '2', files: [] },
      q12: { text: '1', files: [] },
      q13: { text: '0', files: [] },
      q14: { text: '0', files: [] },
      q15: { text: '0', files: [] },
      q16: { text: 'Monsoon drive initiated. Increased focus on street food.', files: [] }
    }
  },
  {
    id: 'sub-2025-08',
    month: '2025-08',
    submittedBy: 'FSO Rajesh Kumar',
    submittedAt: '2025-09-02T10:00:00',
    district: 'Chennai',
    designation: 'Food Safety Officer',
    answers: {
      q1:  { text: '391', files: [] },
      q2:  { text: '25', files: [] },
      q3:  { text: '6', files: [] },
      q4:  { text: '5', files: [] },
      q5:  { text: '2', files: [] },
      q6:  { text: '0', files: [] },
      q7:  { text: '1', files: [] },
      q8:  { text: '2', files: [] },
      q9:  { text: '0', files: [] },
      q10: { text: '4', files: [] },
      q11: { text: '2', files: [] },
      q12: { text: '0', files: [] },
      q13: { text: '2', files: [] },
      q14: { text: '1', files: [] },
      q15: { text: '0', files: [] },
      q16: { text: 'High inspection count due to Onam festival drive.', files: [] }
    }
  },
  {
    id: 'sub-2025-09',
    month: '2025-09',
    submittedBy: 'FSO Rajesh Kumar',
    submittedAt: '2025-10-05T09:30:00',
    district: 'Chennai',
    designation: 'Food Safety Officer',
    answers: {
      q1:  { text: '392', files: [] },
      q2:  { text: '20', files: [] },
      q3:  { text: '4', files: [] },
      q4:  { text: '3', files: [] },
      q5:  { text: '1', files: [] },
      q6:  { text: '0', files: [] },
      q7:  { text: '0', files: [] },
      q8:  { text: '1', files: [] },
      q9:  { text: '0', files: [] },
      q10: { text: '2', files: [] },
      q11: { text: '1', files: [] },
      q12: { text: '0', files: [] },
      q13: { text: '0', files: [] },
      q14: { text: '0', files: [] },
      q15: { text: '0', files: [] },
      q16: { text: 'Normal month, no special drives.', files: [] }
    }
  },
  {
    id: 'sub-2025-10',
    month: '2025-10',
    submittedBy: 'FSO Rajesh Kumar',
    submittedAt: '2025-11-03T10:00:00',
    district: 'Chennai',
    designation: 'Food Safety Officer',
    answers: {
      q1:  { text: '392', files: [] },
      q2:  { text: '28', files: [] },
      q3:  { text: '7', files: [] },
      q4:  { text: '6', files: [] },
      q5:  { text: '0', files: [] },
      q6:  { text: '2', files: [] },
      q7:  { text: '2', files: [] },
      q8:  { text: '3', files: [] },
      q9:  { text: '1', files: [] },
      q10: { text: '5', files: [] },
      q11: { text: '3', files: [] },
      q12: { text: '1', files: [] },
      q13: { text: '1', files: [] },
      q14: { text: '0', files: [] },
      q15: { text: '0', files: [] },
      q16: { text: 'Diwali special drive conducted. 7 samples collected.', files: [] }
    }
  },
  {
    id: 'sub-2025-11',
    month: '2025-11',
    submittedBy: 'FSO Rajesh Kumar',
    submittedAt: '2025-12-04T11:00:00',
    district: 'Chennai',
    designation: 'Food Safety Officer',
    answers: {
      q1:  { text: '393', files: [] },
      q2:  { text: '21', files: [] },
      q3:  { text: '3', files: [] },
      q4:  { text: '3', files: [] },
      q5:  { text: '0', files: [] },
      q6:  { text: '0', files: [] },
      q7:  { text: '1', files: [] },
      q8:  { text: '1', files: [] },
      q9:  { text: '0', files: [] },
      q10: { text: '2', files: [] },
      q11: { text: '1', files: [] },
      q12: { text: '0', files: [] },
      q13: { text: '0', files: [] },
      q14: { text: '0', files: [] },
      q15: { text: '0', files: [] },
      q16: { text: 'Routine inspections completed.', files: [] }
    }
  },
  {
    id: 'sub-2025-12',
    month: '2025-12',
    submittedBy: 'FSO Rajesh Kumar',
    submittedAt: '2026-01-05T09:00:00',
    district: 'Chennai',
    designation: 'Food Safety Officer',
    answers: {
      q1:  { text: '393', files: [] },
      q2:  { text: '24', files: [] },
      q3:  { text: '5', files: [] },
      q4:  { text: '4', files: [] },
      q5:  { text: '1', files: [] },
      q6:  { text: '0', files: [] },
      q7:  { text: '0', files: [] },
      q8:  { text: '2', files: [] },
      q9:  { text: '0', files: [] },
      q10: { text: '3', files: [] },
      q11: { text: '1', files: [] },
      q12: { text: '0', files: [] },
      q13: { text: '1', files: [] },
      q14: { text: '0', files: [] },
      q15: { text: '0', files: [] },
      q16: { text: 'Christmas period drive. Bakeries inspected heavily.', files: [] }
    }
  },
  {
    id: 'sub-2026-01',
    month: '2026-01',
    submittedBy: 'FSO Rajesh Kumar',
    submittedAt: '2026-02-02T10:30:00',
    district: 'Chennai',
    designation: 'Food Safety Officer',
    answers: {
      q1:  { text: '385', files: [] },
      q2:  { text: '16', files: [] },
      q3:  { text: '2', files: [] },
      q4:  { text: '2', files: [] },
      q5:  { text: '0', files: [] },
      q6:  { text: '0', files: [] },
      q7:  { text: '0', files: [] },
      q8:  { text: '1', files: [] },
      q9:  { text: '0', files: [] },
      q10: { text: '1', files: [] },
      q11: { text: '0', files: [] },
      q12: { text: '0', files: [] },
      q13: { text: '0', files: [] },
      q14: { text: '0', files: [] },
      q15: { text: '0', files: [] },
      q16: { text: 'Low activity month due to year-end transfers.', files: [] }
    }
  },
  {
    id: 'sub-2026-02',
    month: '2026-02',
    submittedBy: 'FSO Rajesh Kumar',
    submittedAt: '2026-03-03T10:00:00',
    district: 'Chennai',
    designation: 'Food Safety Officer',
    answers: {
      q1:  { text: '386', files: [] },
      q2:  { text: '18', files: [] },
      q3:  { text: '3', files: [] },
      q4:  { text: '3', files: [] },
      q5:  { text: '0', files: [] },
      q6:  { text: '0', files: [] },
      q7:  { text: '1', files: [] },
      q8:  { text: '1', files: [] },
      q9:  { text: '0', files: [] },
      q10: { text: '2', files: [] },
      q11: { text: '1', files: [] },
      q12: { text: '0', files: [] },
      q13: { text: '0', files: [] },
      q14: { text: '0', files: [] },
      q15: { text: '0', files: [] },
      q16: { text: 'Normal inspections. One sample found substandard.', files: [] }
    }
  },
  {
    id: 'sub-2026-03',
    month: '2026-03',
    submittedBy: 'FSO Rajesh Kumar',
    submittedAt: '2026-04-04T09:30:00',
    district: 'Chennai',
    designation: 'Food Safety Officer',
    answers: {
      q1:  { text: '386', files: [] },
      q2:  { text: '22', files: [] },
      q3:  { text: '4', files: [] },
      q4:  { text: '3', files: [] },
      q5:  { text: '0', files: [] },
      q6:  { text: '1', files: [] },
      q7:  { text: '1', files: [] },
      q8:  { text: '2', files: [] },
      q9:  { text: '0', files: [] },
      q10: { text: '3', files: [] },
      q11: { text: '1', files: [] },
      q12: { text: '0', files: [] },
      q13: { text: '1', files: [] },
      q14: { text: '0', files: [] },
      q15: { text: '0', files: [] },
      q16: { text: 'Year-end activity. License renewals follow-up completed.', files: [] }
    }
  },
  {
    id: 'sub-2026-04',
    month: '2026-04',
    submittedBy: 'FSO Rajesh Kumar',
    submittedAt: '2026-05-05T10:00:00',
    district: 'Chennai',
    designation: 'Food Safety Officer',
    answers: {
      q1:  { text: '387', files: [] },
      q2:  { text: '20', files: [] },
      q3:  { text: '3', files: [] },
      q4:  { text: '3', files: [] },
      q5:  { text: '1', files: [] },
      q6:  { text: '0', files: [] },
      q7:  { text: '0', files: [] },
      q8:  { text: '1', files: [] },
      q9:  { text: '0', files: [] },
      q10: { text: '2', files: [] },
      q11: { text: '1', files: [] },
      q12: { text: '0', files: [] },
      q13: { text: '0', files: [] },
      q14: { text: '0', files: [] },
      q15: { text: '0', files: [] },
      q16: { text: 'New FY started. 3 new FBO registrations processed.', files: [] }
    }
  },
  {
    // ✅ EXACT DATA FROM PDF — May 2026 Monthly Return
    id: 'sub-2026-05',
    month: '2026-05',
    submittedBy: 'FSO Rajesh Kumar',
    submittedAt: '2026-06-02T10:00:00',
    district: 'Chennai',
    designation: 'Food Safety Officer',
    answers: {
      q1:  { text: '387', files: [] },
      q2:  { text: '21', files: [] },
      q3:  { text: '3', files: [] },
      q4:  { text: '1', files: [] },
      q5:  { text: '0', files: [] },
      q6:  { text: '0', files: [] },
      q7:  { text: '1', files: [] },
      q8:  { text: '0', files: [] },
      q9:  { text: '0', files: [] },
      q10: { text: '2', files: [] },
      q11: { text: '1', files: [] },
      q12: { text: '0', files: [] },
      q13: { text: '0', files: [] },
      q14: { text: '0', files: [] },
      q15: { text: '0', files: [] },
      q16: { text: 'May 2026 return. 3 samples sent to lab, 1 analyzed (conform to standard). 2 adjudication cases pending.', files: [] }
    }
  }
];

const SEED_QUESTIONS = [
  { id: 'q1',  bold: true, type: 'text',   label: 'Total number of FBOs registered/licensed under the Act' },
  { id: 'q2',  bold: true, type: 'text',   label: 'Number of inspections carried out during the month' },
  { id: 'q3',  bold: true, type: 'text',   label: 'Number of food samples collected / lifted' },
  { id: 'q4',  bold: true, type: 'text',   label: 'Number of samples sent to laboratory for analysis' },
  { id: 'q5',  bold: true, type: 'text',   label: 'Number of samples found Unsafe' },
  { id: 'q6',  bold: true, type: 'text',   label: 'Number of samples found Sub-standard' },
  { id: 'q7',  bold: true, type: 'text',   label: 'Number of samples found Conform to Standard' },
  { id: 'q8',  bold: true, type: 'text',   label: 'Number of samples found Misbranded / Misleading' },
  { id: 'q9',  bold: true, type: 'text',   label: 'Number of samples found with Extraneous Matter' },
  { id: 'q10', bold: true, type: 'text',   label: 'Total number of Adjudication cases pending' },
  { id: 'q11', bold: true, type: 'text',   label: 'Number of Adjudication cases disposed off during the month' },
  { id: 'q12', bold: true, type: 'text',   label: 'Total fine imposed (in Rs.)' },
  { id: 'q13', bold: true, type: 'text',   label: 'Number of prosecutions launched' },
  { id: 'q14', bold: true, type: 'text',   label: 'Number of cases in Special Court / JMFC' },
  { id: 'q15', bold: true, type: 'text',   label: 'Number of Special Drives conducted' },
  { id: 'q16', bold: true, type: 'textarea', label: 'Remarks / Special observations for this month' },
  { id: 'q17', bold: true, type: 'file',   label: 'Upload Annexure (Lab Reports, Inspection Sheets, etc.)' }
];

window.SEED_SUBMISSIONS = SEED_SUBMISSIONS;
window.SEED_QUESTIONS = SEED_QUESTIONS;
